# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'DemoMRSelectCountryWithPods' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoMRSelectCountryWithPods'
pod 'MRSelectCountry', '~> 1.0.4'

end
